# Generated by Django 2.2.7 on 2020-01-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
